language: dart
sudo: false
dart:
  - dev
cache:
  directories:
    - $HOME/.pub-cache
dart_task:
  - test
  - test -p chrome
  - test -p firefox
  - dartfmt
  - dartanalyzer
  - dartanalyzer: --no-strong .
